# Builds

[tasks.build]
workspace = false
dependencies = [
  "build-linux",
  "build-windows"
]

[tasks.build-linux]
workspace = false
condition = { platforms = ["linux"] }
script_runner = "@shell"
script = [
  "cargo build --release -p game",
  "mkdir -p ./builds/linux",
  "cp target/release/game ./builds/linux/game"
]

[tasks.build-windows]
workspace = false
condition = { platforms = ["windows"] }
script_runner = "@shell"
script = [
  "cargo build --release -p game",
  "mkdir -p ./builds/windows",
  "cp target/release/game.exe ./builds/windows/game.exe"
]

[tasks.build-web]
workspace = false
script_runner = "@shell"
script = [
  "rm -rf ./builds/web",
  "mkdir -p ./builds/web/assets",
  "wasm-pack build engine --target web --release --out-dir ../builds/web",
  "cp ./engine/index.html ./builds/web/index.html",
  "cp -r ./engine/assets ./builds/web/assets"
]

# Execution

[tasks.dev]
workspace = false
script = [
  "cargo run -p game"
]

[tasks.prod]
workspace = false
dependencies = [
  "prod-linux",
  "prod-windows"
]

[tasks.prod-linux]
workspace = false
condition = { platforms = ["linux"] }
command = "./builds/linux/game"

[tasks.prod-windows]
workspace = false
condition = { platforms = ["windows"] }
command = "./builds/windows/game.exe"

[tasks.web]
workspace = false
script_runner = "@shell"
script = [
  "echo http://localhost:8050",
  "python3 -m http.server 8050 --directory ./builds/web"
]
