[tasks.build-desktop]
workspace = false
script_runner = "@shell"
script = [
  "cargo build --release -p game",
  "mkdir -p ./builds/desktop",
  "cp target/release/game.exe ./builds/desktop"
]

[tasks.build-web]
workspace = false
script_runner = "@shell"
script = [
  "rm -rf ./builds/web",
  "mkdir -p ./builds/web/assets",
  "wasm-pack build engine --target web --release --out-dir ../builds/web",
  "cp ./engine/index.html ./builds/web/index.html",
  "cp -r ./engine/assets ./builds/web/assets"
]

[tasks.dev]
workspace = false
script = [
  "cargo run -p game"
]

[tasks.prod]
workspace = false
command = "./builds/desktop/game"

[tasks.web]
workspace = false
script_runner = "@shell"
script = [
  "python3 -m http.server 8050 --directory ./builds/web"
]
